es:
  build: es2
  ports:
   - "9200:9200"
  expose:
   - "9200"
  volumes:
   - /data/download/ttstore/es/logs:/var/log/elasticsearch
   - /data/download/ttstore/es/data:/usr/share/elasticsearch/data
   - /data/download/ttstore/es/work:/work
ttserver:
  build: server
  ports:
   - "8000:8000"
  expose:
   - "8000"
  volumes:
   - ~/project/ttstore-admin/server:/opt/ttserver
  links:
   - "es:es"
web:
  build: nginx-spdy
  ports:
   - "443:443"
   - "80:80"
  volumes:
   - ~/project/ttstore-admin/back2:/data/wwww
   - /data/download/ttstore/ngnix/logs:/etc/nginx/logs
  links:
   - "es:es"
   - "ttserver:ttserver"
