es:
  image: jmorille/es
  ports:
   - "9200:9200"
  expose:
   - "9200"
  volumes:
   - /data2/ttstore/logs:/logs
   - /data2/ttstore/data:/data
   - /data2/ttstore/work:/work
   - /data2/ttstore/tmp:/tmp
ttserver:
  image: jmorille/ttserver
  ports:
   - "8000:8000"
  expose:
   - "8000"
  volumes:
   - ~/project/ttstore-admin/server:/opt/ttserver
  links:
   - "es:es"
web:
  image: jmorille/nginx-spdy
  ports:
   - "443:443"
   - "80:80"
  volumes:
   - ~/project/ttstore-admin/back:/data/wwww
   - /data2/ttsore-ngnix/logs:/etc/nginx/logs
  links:
   - "es:es"
   - "ttserver:ttserver"
