es:
  image: jmorille/elasticsearch
  ports:
   - "9200:9200"
  expose:
   - "9200"
  volumes:
   - /data2/ttstore/logs:/opt/elasticsearch-1.3.2/logs
   - /data2/ttstore/data:/opt/elasticsearch-1.3.2/data
ttserver:
  image: jmorille/ttserver
  ports:
   - "8000:8000"
  expose:
   - "8000"
  volumes:
   - /home/a000cqp/project/ttstore-admin/server:/opt/ttserver
  links:
   - "es:es"
web:
  image: jmorille/nginx-spdy
  ports:
   - "443:443"
   - "80:80"
  volumes:
   - /home/a000cqp/project/ttstore-admin/back:/data/wwww
   - /data2/ttsore-ngnix/logs:/etc/nginx/logs
  links:
   - "es:es"
   - "ttserver:ttserver"
