es:
  image: jmorille/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /data2/ttstore/logs:/opt/elasticsearch-1.3.2/logs
    - /data2/ttstore/data:/opt/elasticsearch-1.3.2/data
web:
  image: jmorille/ngnix-spdy
 ports:
    - "80:80"
    - "443:443"
